### ISSUE TITLE
Add CI Support

### ISSUE THREAD

**Issue by countableSet** [countableSet/latex-builder#1]
`circle.yml` suggestion:
```
machine:
    node:
        version: 
            0.11.8
    java:
        version:
            oraclejdk8
    services:
        - docker
test:
    override:
        - gradle test
        - grunt test
```

[Docker Service](https://circleci.com/docs/docker) documentation.
